# -*- coding: utf-8 -*-
DEBUG = True
# 数据库信息输出
SQLALCHEMY_ECHO = True
SQLALCHEMY_DATABASE_URI = "mysql://root:123456@127.0.0.1/mysql"
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ENCODING = 'utf-8'